// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcqgkdfuamjcpsngxzzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jcWdrZGZ1YW1qY3Bzbmd4enprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Mjc2NzIsImV4cCI6MjA3MTMwMzY3Mn0.zNkgc_cdMmhd6RMDC9Spw0SZguw3xs1vQhjOPQPymXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});